services:
  site:
    image: site:latest
    ports:
      - "3333:3333"
    networks:
      - rede-compose
    depends_on:
      - db

  db:
    image: db:latest
    ports:
      - "3307:3306"
    networks:
      - rede-compose

networks:
  rede-compose:
    driver: bridge
