# Imagem do banco de dados
FROM mysql:latest

ENV MYSQL_DATABASE=runguard
ENV MYSQL_USER=usuario
ENV MYSQL_PASSWORD=12345
ENV MYSQL_ROOT_PASSWORD=urubu100

COPY BancoDeDados-RunGuard.sql /docker-entrypoint-initdb.d/